# Generated by Django 4.0 on 2022-06-21 08:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCustomRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_flag', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('db_source', models.CharField(choices=[('akso_test', '手机端报销测试库'), ('scanner', '进项税扫票测试库'), ('akso_local', '手机端报销本地库')], max_length=200, verbose_name='数据来源')),
                ('table_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='表(视图)名')),
                ('list_fields', models.TextField(blank=True, null=True, verbose_name='展示字段(一行一个，默认全部字段)')),
                ('search_fields', models.TextField(blank=True, null=True, verbose_name='查询字段(一行一个)')),
                ('view_sql', models.TextField(blank=True, null=True, verbose_name='定制视图sql')),
                ('verbose_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='展示名称')),
            ],
            options={
                'verbose_name': '后台定制记录',
                'verbose_name_plural': '后台定制记录',
                'db_table': 'ad_custom_record',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InspectDbRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_source', models.CharField(choices=[('akso_test', '手机端报销测试库'), ('scanner', '进项税扫票测试库'), ('akso_local', '手机端报销本地库')], max_length=200, verbose_name='数据来源')),
                ('model_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='model名称')),
                ('inspectdb_records', tinymce.models.HTMLField(verbose_name='迁移记录')),
                ('is_changed', models.CharField(default='N', max_length=3, verbose_name='是否修改过')),
            ],
            options={
                'verbose_name': '迁移记录',
                'verbose_name_plural': '迁移记录',
                'db_table': 'ad_inspectdb_records',
                'ordering': ['-id'],
            },
        ),
    ]
