# Generated by Django 4.0 on 2022-06-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register_table', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincustomrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='users.user'),
        ),
        migrations.AddField(
            model_name='admincustomrecord',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, db_column='last_updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_updated_by', to='users.user'),
        ),
    ]
