# Generated by Django 4.0 on 2022-06-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_table', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincustomrecord',
            name='db_source',
            field=models.CharField(choices=[('akso_test', '手机端报销测试库'), ('scanner', '进项税扫票测试库'), ('akso_local', '手机端报销本地库'), ('akso', '测试不存在的库')], max_length=200, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='inspectdbrecord',
            name='db_source',
            field=models.CharField(choices=[('akso_test', '手机端报销测试库'), ('scanner', '进项税扫票测试库'), ('akso_local', '手机端报销本地库'), ('akso', '测试不存在的库')], max_length=200, verbose_name='数据来源'),
        ),
    ]
