# Generated by Django 4.0 on 2022-06-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_table', '0003_alter_admincustomrecord_db_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectdbrecord',
            name='inspectdb_records',
            field=models.TextField(blank=True, null=True, verbose_name='迁移记录'),
        ),
    ]
