# Generated by Django 4.0 on 2022-06-30 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_table', '0004_alter_inspectdbrecord_inspectdb_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincustomrecord',
            name='view_sql',
        ),
    ]
