# Generated by Django 4.0 on 2022-07-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_member_of'),
        ('register_table', '0005_remove_admincustomrecord_view_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincustomrecord',
            name='db_source',
            field=models.CharField(choices=[('akso_test', '手机端报销测试库'), ('scanner', '进项税扫票测试库'), ('akso_local', '手机端报销本地库'), ('zhaopin', '招聘测试库')], max_length=200, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='inspectdbrecord',
            name='db_source',
            field=models.CharField(choices=[('akso_test', '手机端报销测试库'), ('scanner', '进项税扫票测试库'), ('akso_local', '手机端报销本地库'), ('zhaopin', '招聘测试库')], max_length=200, verbose_name='数据来源'),
        ),
        migrations.CreateModel(
            name='DbSourcePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_source', models.CharField(choices=[('akso_test', '手机端报销测试库'), ('scanner', '进项税扫票测试库'), ('akso_local', '手机端报销本地库'), ('zhaopin', '招聘测试库')], max_length=200, verbose_name='数据来源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
            options={
                'verbose_name': '数据库权限表',
                'verbose_name_plural': '数据库权限表',
                'db_table': 'ad_dbsource_permission',
                'ordering': ['-id'],
            },
        ),
    ]
