# Generated by Django 4.0 on 2022-08-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_table', '0007_alter_admincustomrecord_db_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincustomrecord',
            name='db_source',
            field=models.CharField(choices=[('zhaopin_test', '招聘测试库'), ('zhaopin', '招聘生产库'), ('javakaoqin', 'java考勤生产库')], max_length=200, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='dbsourcepermission',
            name='db_source',
            field=models.CharField(choices=[('zhaopin_test', '招聘测试库'), ('zhaopin', '招聘生产库'), ('javakaoqin', 'java考勤生产库')], max_length=200, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='inspectdbrecord',
            name='db_source',
            field=models.CharField(choices=[('zhaopin_test', '招聘测试库'), ('zhaopin', '招聘生产库'), ('javakaoqin', 'java考勤生产库')], max_length=200, verbose_name='数据来源'),
        ),
    ]
