# Generated by Django 4.0 on 2022-08-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_table', '0008_alter_admincustomrecord_db_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincustomrecord',
            name='admin_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='生成的admin名称'),
        ),
    ]
