# Generated by Django 4.0 on 2022-08-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_table', '0009_admincustomrecord_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincustomrecord',
            name='alter_fields',
            field=models.TextField(blank=True, help_text='请确认是否有修改权限', null=True, verbose_name='修改字段(一行一个)'),
        ),
        migrations.AddField(
            model_name='admincustomrecord',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='是否允许删除数据'),
        ),
    ]
