# Generated by Django 4.0 on 2022-06-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_of',
            field=models.TextField(blank=True, null=True),
        ),
    ]
